export const SUCCESS_CODE = 200;
export const SUCCESSFUL_RESOURCE_CREATION_CODE = 201;
export const ALREADY_EXISTS_CONFLICT_CODE = 409;
export const INTERNAL_SERVER_ERROR_CODE = 500;
export const NOT_FOUND_CODE = 404;
export const UNAUTHENTICATED_CODE = 401;
